export const ORDER_ALL_REQUEST = "ORDER_ALL_REQUEST";
export const ORDER_ALL_SUCCESS = "ORDER_ALL_SUCCESS";
export const ORDER_ALL_FAIL = "ORDER_ALL_FAIL";
export const ORDER_ALL_RESET = "ORDER_ALL_RESET";

export const ORDER_SALES_REQUEST = "ORDER_SALES_REQUEST";
export const ORDER_SALES_SUCCESS = "ORDER_SALES_SUCCESS";
export const ORDER_SALES_FAIL = "ORDER_SALES_FAIL";
export const ORDER_SALES_RESET = "ORDER_SALES_RESET";

export const ORDER_ALL_ACTIVE_REQUEST = "ORDER_ALL_ACTIVE_REQUEST";
export const ORDER_ALL_ACTIVE_SUCCESS = "ORDER_ALL_ACTIVE_SUCCESS";
export const ORDER_ALL_ACTIVE_FAIL = "ORDER_ALL_ACTIVE_FAIL";
export const ORDER_ALL_ACTIVE_RESET = "ORDER_ALL_ACTIVE_RESET";

export const ORDER_LIST_ALL_REQUEST = "ORDER_LIST_ALL_REQUEST";
export const ORDER_LIST_ALL_SUCCESS = "ORDER_LIST_ALL_SUCCESS";
export const ORDER_LIST_ALL_FAIL = "ORDER_LIST_ALL_FAIL";
export const ORDER_LIST_ALL_RESET = "ORDER_LIST_ALL_RESET";

export const ORDER_DELIVERY_REQUEST = "ORDER_DELIVERY_REQUEST";
export const ORDER_DELIVERY_SUCCESS = "ORDER_DELIVERY_SUCCESS";
export const ORDER_DELIVERY_FAIL = "ORDER_DELIVERY_FAIL";
export const ORDER_DELIVERY_RESET = "ORDER_DELIVERY_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET";

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const ORDER_UPDATE_RESET = "ORDER_UPDATE_RESET";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";
export const ORDER_DELETE_RESET = "ORDER_DELETE_RESET";
